app/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from app import views

urlpatterns = [
    # Matches any html file - to be used for gentella
    # Avoid using your .html in your resources.
    # Or create a separate django app.
    re_path(r'^.*\.html', views.pages, name='pages'),

    # The home page
    path('', views.index, name='home'),
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('processdata.urls')),
    path('', include('app.urls')),
    path('testing/', include(('testing.urls','testing' ), namespace='testing')),
      # add this
]

processdata/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('maps.html', views.mapspage, name='maps'),
    path('report', views.report, name='report'),
    path('trends', views.trends, name='trends'),
    path('cases', views.global_cases, name='cases'),
    path('realtime_growth', views.realtime_growth, name='realtime_growth'),
    path('daily_growth', views.daily_growth, name='daily_growth'),
    path('daily_report', views.daily_report, name='daily_report')
]

testing/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this
from testing import views

urlpatterns = [
    path('', views.index, name='tester'),
    path('/take', views.tester, name='tester1'),
      # add this
]

app/models.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

testing/models.py
from django.db import models

# Create your models here.
class Questions(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    # assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    question = models.CharField(max_length=1000)
    points = models.IntegerField(null=True, blank=True, default=0)

    def __str__(self):
        return self.question

class Options(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Questions, on_delete=models.CASCADE)
    option = models.CharField(max_length=1000)
    points = models.IntegerField(null=True, blank=True, default=0)

    def __str__(self):
        return self.Question

app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.http import HttpResponse


def index(request):
    return render(request, "index.html")


def pages(request):
    context = {}
    # All resource paths end in .html.
    # Pick out the html file name from the url. And load that template.
    try:
        load_template = request.path.split('/')[-1]
        template = loader.get_template('pages/' + load_template)
        return HttpResponse(template.render(context, request))

    except:
        template = loader.get_template( 'pages/error-404.html' )
        return HttpResponse(template.render(context, request))

processdata/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template import loader

import json

from . import getdata, maps





def report(request):
    df = getdata.daily_report(date_string=None)
    df = df[['Confirmed', 'Deaths', 'Recovered']].sum()
    death_rate = f'{(df.Deaths / df.Confirmed)*100:.02f}%'

    data = {
        'num_confirmed': int(df.Confirmed),
        'num_recovered': int(df.Recovered),
        'num_deaths': int(df.Deaths),
        'death_rate': death_rate
    }

    data = json.dumps(data)

    return HttpResponse(data, content_type='application/json')


def trends(request):
    df = getdata.percentage_trends()

    data = {
        'confirmed_trend': int(round(df.Confirmed)),
        'deaths_trend': int(round(df.Deaths)),
        'recovered_trend': int(round(df.Recovered)),
        'death_rate_trend': float(df.Death_rate)
    }

    data = json.dumps(data)

    return HttpResponse(data, content_type='application/json')


def global_cases(request):
    df = getdata.global_cases()
    return HttpResponse(df.to_json(orient='records'), content_type='application/json')


def world_map():
    plot_div = maps.world_map()
    return {'world_map': plot_div}


def realtime_growth(request):
    import pandas as pd
    df = getdata.realtime_growth();

    df.index = pd.to_datetime(df.index)
    df.index = df.index.strftime('%Y-%m-%d')

    return HttpResponse(df.to_json(orient='columns'), content_type='application/json')


def daily_growth(request):
    df_confirmed = getdata.daily_confirmed()[['date', 'World']]
    df_deaths = getdata.daily_deaths()[['date', 'World']]

    df_confirmed = df_confirmed.set_index('date')
    df_deaths = df_deaths.set_index('date')

    json_string = '{' + \
        '"confirmed": ' + df_confirmed.to_json(orient='columns') + ',' + \
        '"deaths": ' + df_deaths.to_json(orient='columns') + \
    '}'

    return HttpResponse(json_string, content_type='application/json')


def daily_report(request):
    df = getdata.daily_report()

    df.drop(['FIPS', 'Admin2', 'Province_State', 'Country_Region', 'Last_Update', 'Deaths', 'Recovered', 'Active', 'Incident_Rate', 'Case_Fatality_Ratio'], axis=1, inplace=True)

    return HttpResponse(df.to_json(orient='columns'), content_type='application/json')


def mapspage(request):
    plot_div = maps.usa_map()
    return render(request, template_name='pages/maps.html', context={'usa_map': plot_div})

def index(request): 
    
    return render(request, template_name='index.html')

testing/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.http import HttpResponse
from testing.models import Questions


def index(request):
    return render(request, "testing.html")

def tester(request):
    question =Questions.objects.all()
    return render(request, "testingQ.html", {"questions": question})

core/templates/includes/footer.html
<!-- Footer -->
<footer class="footer">
  <div class="row align-items-center justify-content-xl-between">
    <div class="col-xl-6">
      <div class="text-center text-xl-left ">
        <a href="https://github.com/BrianRuizy/covid19-dashboard" class="font-weight-bold ml-1 text-muted"
          target="_blank">covid19-ehisproject</a>
      </div>
    </div>
    <div class="col-xl-6">
      <div class="text-center text-xl-right ">
        <a href="" class="font-weight-bold ml-1 text-muted" target="_blank">@joshijax
      </div>
    </div>
  </div>
</footer>

core/templates/includes/header.html
{% load humanize %}
{% load trend %}

<!-- Header -->
<div class="header pb-8 pt-5 pt-md-6 bg-secondary">
    <div class="container-fluid">
        <div class="header-body">
        <!-- Card stats -->
        <div class="row">
            <div class="col-xl-3 col-lg-6">
            <div class="card shadow card-stats mb-4 mb-xl-0 fade-in-top">
                <div class="card-body ">
                <div class="row">
                    <div class="col">
                    <h5 class="card-title text-uppercase text-muted mb-0">Confirmed</h5>
                    <span id="daily_confirmed_label" class="h2 font-weight-bold mb-0">0</span>
                    </div>
                    <div class="col-auto">
                    <div class="icon icon-shape bg-primary text-white rounded-circle shadow">
                        <i class="fas fa-virus"></i>
                    </div>
                    </div>
                </div>
                <p class="mt-3 mb-0 text-muted text-sm">
                    <span id="trend_confirmed_label" class="mr-2">+0%</span>
                    <span class="text-nowrap">Since last week</span>
                </p>
                </div>
            </div>
            </div>
            <div class="col-xl-3 col-lg-6">
            <div class="card shadow card-stats mb-4 mb-xl-0 fade-in-top">
                <div class="card-body ">
                <div class="row">
                    <div class="col">
                    <h5 class="card-title text-uppercase text-muted mb-0">Recovered</h5>
                    <span id="daily_recovered_label" class="h2 font-weight-bold mb-0">0</span>
                    </div>
                    <div class="col-auto">
                    <div class="icon icon-shape bg-green text-white rounded-circle shadow">
                        <i class="fas fa-heartbeat"></i>
                    </div>
                    </div>
                </div>
                <p class="mt-3 mb-0 text-muted text-sm">
                    <span id="trend_recovered_label" class="mr-2">+0%</span>
                    <span class="text-nowrap">Since last week</span>
                </p>
                </div>
            </div>
            </div>
            <div class="col-xl-3 col-lg-6">
            <div class="card shadow card-stats mb-4 mb-xl-0 fade-in-top">
                <div class="card-body ">
                <div class="row">
                    <div class="col">
                    <h5 class="card-title text-uppercase text-muted mb-0">Deaths</h5>
                    <span id="daily_deaths_label" class="h2 font-weight-bold mb-0">0</span>
                    </div>
                    <div class="col-auto">
                    <div class="icon icon-shape bg-danger text-white rounded-circle shadow">
                        <i class="fa fa-skull-crossbones"></i>
                    </div>
                    </div>
                </div>
                <p class="mt-3 mb-0 text-muted text-sm">
                    <span id="trend_deaths_label" class="mr-2">+0%</span>
                    <span class="text-nowrap">Since last week</span>
                </p>
                </div>
            </div>
            </div>
            <div class="col-xl-3 col-lg-6">
            <div class="card shadow card-stats mb-4 mb-xl-0 fade-in-top">
                <div class="card-body ">
                <div class="row">
                    <div class="col">
                    <h5 class="card-title text-uppercase text-muted mb-0">Death Rate</h5>
                    <span id="daily_death_rate_label" class="h2 font-weight-bold mb-0">0</span>
                    </div>
                    <div class="col-auto">
                    <div class="icon icon-shape bg-warning text-white rounded-circle shadow">
                        <i class="fa fa-percent"></i>
                    </div>
                    </div>
                </div>
                <p class="mt-3 mb-0 text-muted text-sm">
                    <span id="trend_death_rate_label" class="mr-2">+0</span>
                    <span class="text-nowrap">Since last week</span>
                </p>
                </div>
            </div>
            </div>
        </div>
        </div>
    </div>
</div>

core/templates/includes/scripts.html
  <!--   Core   -->
  {% load static %}
  <script src="/static/assets/js/plugins/jquery/dist/jquery.min.js"></script>
  <script src="/static/assets/js/plugins/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

  <!--   Argon JS   -->
  <script src="/static/assets/js/argon-dashboard.min.js?v=1.1.0"></script>
  <script src="{% static 'js/dento.bundle.js' %}"></script>
  <!-- Active js -->
  <script src="{% static 'js/default-assets/active.js' %}"></script>

core/templates/includes/sidenav.html
<div id="preloader">
    <div class="preload-content">
        <div id="dento-load"></div>
    </div>
</div>
  <nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-dark bg-dark" id="sidenav-main">
    <div class="container-fluid">
      <!-- Toggler -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Brand -->
      <a class="navbar-brand pt-0" href="/">
        {% comment %} <img src="/static/assets/img/brand/blue.png" class="navbar-brand-img" alt="..."> {% endcomment %}
        Covid19 Tester     
      </a>
      <!-- User -->
      <ul class="nav align-items-center d-md-none">
        <li class="nav-item dropdown">
          <a class="nav-link nav-link-icon" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-info-circle"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right" aria-labelledby="navbar-default_dropdown_1">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>

      </ul>
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Collapse header -->
        <div class="navbar-collapse-header d-md-none">
          <div class="row">
            <div class="col-6 collapse-brand">
              <a href="./">
                {% comment %} <img src="/static/assets/img/brand/white.png"> {% endcomment %}
                Covid19 Tester
              </a>
            </div>
            <div class="col-6 collapse-close">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                <span></span>
                <span></span>
              </button>
            </div>
          </div>
        </div>

        <!-- Navigation -->
        <ul class="navbar-nav">
          <li class="nav-item home-item">
          <a class=" nav-link active text-light fade-in-left " href="/"><i class="fas fa-home text-primary "></i>Home
            </a>
          </li>

          <li class="nav-item maps-item">
            <a class="nav-link text-light fade-in-left " href="/maps.html">
              <i class="fas fa-map-marked-alt text-warning"></i>Maps
            </a>
          </li>
        </ul>
        <!-- Divider -->
        <hr class="my-3">
        <!-- Heading -->
        <!-- Navigation -->
        <ul class="navbar-nav mb-md-3 ">

          <li class="nav-item">
            <a class="nav-link text-muted fade-in-left" href="{% url 'testing:tester' %}" >
              <i class="fa fa-medkit " style="font-size:1.1rem;"></i>Test for covid19
            </a>
          </li>

          {% comment %} <li class="nav-item data-item">
            <a class="nav-link text-muted fade-in-left" href="/data.html">
              <i class="fas fa-database"></i>Data
            </a>
          </li> {% endcomment %}

        </ul>
      </div>
    </div>
  </nav>

core/templates/includes/sucess.html
<div class="row">
    <div class="col-sm-12">
        <div id="myModal" class="modal fade"  data-keyboard="false" data-backdrop="static">
            <div class="modal-dialog modal-confirm">
                <div class="modal-content">
                    <div class="modal-header justify-content-center" id="modal-header">
                        <div class="icon-box">
                            <i class="material-icons">&#xE876;</i>
                        </div>
                        {% comment %} <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button> {% endcomment %}
                    </div>
                    <div class="modal-body text-center">
                        <h4 id="result1">Great!</h4>	
                        <a href="">Contact a doctor</p>
                        <button onClick="window.location.reload();" class="btn btn-success" data-dismiss="modal"><span>ReTake Test</span> <i class="material-icons">&#xE5C8;</i></button>
                    </div>
                </div>
            </div>
        </div>  
    </div>
</div>  

core/templates/index.html
{% extends 'layouts/base.html' %}
{% load humanize %}


{% block title %} Home {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    {% include "includes/header.html" %}

    <div class="container-fluid mt--7 bg-secondary">
      <div class="row">
        <div class="col-xl-8 mb-5 mb-xl-0">  <!-- Global interactive Plotly Mabpox -->
          <div class="card shadow fade-in-bottom">
            <div class="card-body plotly worldmap">
              <div id="world_map" class="chart" style="height: 100%;"></div>
            </div>
            <div style="position: absolute; padding:1.25rem 1.5rem;">
                <h6 class="text-uppercase text-muted ls-1 mb-1">Global | Cumulative</h6>
                <h2 class="text-dark mb-0">Mapbox</h2>
            </div>
          </div>
        </div>
        <div class="col-xl-4">  <!-- Growth interactive scatterplot -->
          <div class="card bg-dark shadow fade-in-bottom">
            <div class="card-header bg-transparent">
              <div class="row align-items-center">
                <div class="col">
                  <h6 class="text-uppercase text-light ls-1 mb-1">Global | Cumulative</h6>
                  <h2 class="text-white mb-0">Growth</h2>
                </div>
                <div class="col text-right">
                  <a class="btn btn-sm btn-light" tabindex="0" role="button" data-toggle="popover" data-trigger="focus" title="Info"
                      data-content="Global cumulative growth in cases since collection of data started. Defaulted to logarithmic y-scale">
                      &nbsp;<i class="fas fa-info text-dark">&nbsp;</i>
                    </a>
                </div>
              </div>
            </div>
            <div class="card-body plotly">
              <div id="realtime_growth_chart" class="chart" style="height: 310px;"></div>
            </div>
          </div>
        </div>
      </div>

      <div class="row mt-5">
        <div class="col-xl-8 mb-5 mb-xl-0">   <!-- Global daily growth plot -->
          <div class="card shadow">
            <div class="card-header bg-transparent">
              <div class="row align-items-center">
                <div class="col">
                  <h6 class="text-uppercase text-muted ls-1 mb-1">Global | Daily</h6>
                  <h2 class="mb-0">Daily Growth</h2>
                </div>
                <div class="col text-right">
                  <a class="btn btn-sm btn-white" tabindex="0" role="button" data-toggle="popover" data-trigger="focus" title="Info"
                      data-content="Daily time series of cases. Bars can be stacked for relative adjacent comparison by toggling 'confirmed' cases.">
                      &nbsp;<i class="fas fa-info">&nbsp;</i>
                    </a>
                </div>
              </div>
            </div>

            <div class="card-body plotly">
              <div id="daily_growth_chart" class="chart"style="height: 310px;"></div>
            </div>
          </div>
        </div>

        <div class="col-xl-4">
          <div class="card shadow">
            <div class="card-header bg-transparent">
              <div class="row align-items-center">
                <div class="col">
                  <h6 class="text-uppercase text-muted ls-1 mb-1">Global | Sortable</h6>
                  <h2 class="mb-0">Cases</h2>
                </div>
                <div class="col text-right">
                  <a href="#!" class="btn btn-sm btn-white">
                    &nbsp;<i class="fas fa-download">&nbsp;</i>
                  </a>
                </div>
              </div>
            </div>
            <div class="table-responsive">
              <!-- cases table -->
              <table id="cases_table" class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">Country</th>
                    <th scope="col">Confirmed</th>
                    <th scope="col">Recovered</th>
                    <th scope="col">Deaths</th>
                    <th scope="col">Death Rate %</th>
                  </tr>
                </thead>
                <tbody id="cases_table_body"></tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

      {% include "includes/footer.html" %}

    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}
<script>
$('.nav-item a').removeClass('active');
$('.home-item a').addClass('active');
</script>

<!-- Sortable Tables -->
<script defer src="/static/assets/js/sorttable.js"></script>

<!-- Plotly.js CDN -->
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/plotly.js/1.54.6/plotly.min.js"></script>

<!-- Load and display data -->
<script defer src="/static/assets/js/fetch-data.js"></script>
{% endblock javascripts %}

core/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">

<!-- Static assets - Used to load the Favicon -->
{% load static %}

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>
    COVID-19 Dashboard | {% block title %} COVID test {% endblock %}
  </title>

  <!-- Favicon - loaded as static -->
  <link rel="icon" href="{% static 'assets/img/brand/favicon.ico' %}" type="image/png" media="print" onload="this.media='all'"/>
  <noscript><link rel="icon" href="{% static 'assets/img/brand/favicon.ico' %}" type="image/png"/></noscript>

  <!-- Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" media="print" onload="this.media='all'"/>
  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap"/></noscript>

  <!-- Icons -->
  <script defer src="https://kit.fontawesome.com/189832a678.js" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="/static/assets/css/style.css?v=1.1.0" media="print" onload="this.media='all'"/>
  <noscript><link rel="stylesheet" href="/static/assets/css/style.css?v=1.1.0"/></noscript>

  <!-- Specific CSS goes HERE -->
  {% block stylesheets %}

  {% endblock stylesheets %}

</head>

<body class="">

  {% include "includes/sidenav.html" %}

  <div class="main-content">

    {% block content %}{% endblock content %}

  </div>

  {% include "includes/scripts.html" %}

  <!-- Specific JS goes HERE --> 
  {% block javascripts %}{% endblock javascripts %}

</body>

</html>

core/templates/pages/data.html
{% extends 'layouts/base.html' %}

{% block title %} Data {% endblock title %}

{% block content %}

<div class="container-fluid pt-6 bg-secondary">
    <h2>Data</h2>
    <p>Data sources used throughout the project.</p>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><a href="https://github.com/CSSEGISandData/COVID-19">Johns Hopkins</a></li>
        <li class="list-group-item"><a href="https://github.com/owid/covid-19-data/tree/master/public/data">Our World In Data</a></li>
        <li class="list-group-item"><a href="https://github.com/nytimes/covid-19-data">New York Times</a></li>
    </ul>

    {% include "includes/footer.html" %}
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<script>
$('.nav-item a').removeClass('active');
$('.data-item a').addClass('active');
</script>
{% endblock javascripts %}

core/templates/pages/error-404.html
{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted bg-transparent text-center mt-2 mb-3">
                <h2> Oops! Error 404</h2>
              </div>

              <div class="text-center mb-4">
                Page not found
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

core/templates/pages/maps.html
{% extends 'layouts/base.html' %}

{% block title %} Maps {% endblock title %}

{% block content %}  
<div class="container-fluid pt-6 bg-secondary">
  <h2>Maps</h2>
  <p>Country level maps. More coming soon!</p>
  <div class="row">
    <div class="col-xl-12 mb-5 mb-xl-0">  <!-- Global interactive Plotly Mabpox -->
      <div class="card shadow fade-in-bottom">
        <div class="card-body plotly worldmap">
          <script src="https://cdnjs.cloudflare.com/ajax/libs/plotly.js/1.54.6/plotly.min.js"></script>

          <div class="chart">
            {% autoescape off %}
            {{ usa_map }}
            {% endautoescape %}
          </div>
        </div>
        <div style="position: absolute; padding:1.25rem 1.5rem;">
            <h6 class="text-uppercase text-muted ls-1 mb-1">USA Counties | Per Capita</h6>
            <h2 class="text-dark mb-0">Per 100k Residents</h2>
        </div>
      </div>
    </div>
  </div>
  {% include "includes/footer.html" %}
</div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}
<script>
$('.nav-item a').removeClass('active');
$('.maps-item a').addClass('active');
</script>
{% endblock javascripts %}

core/templates/testing.html
{% extends 'layouts/base.html' %}
{% load humanize %}


{% block title %} Home {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


    <div class="container bg-light" style="display: flex; height: 100vh; align-items: center;">
        <div class="col-md-12 text-center">
            <a href="{% url 'testing:tester1' %}" type="button" class="btn btn-warning">Take Test</a>
            <a href="#" onClick="window.history.back();" type="button" class="btn btn-primary">Cancel</a>
        </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}
<script>
$('.nav-item a').removeClass('active');
$('.home-item a').addClass('active');
</script>

<!-- Sortable Tables -->
<script defer src="/static/assets/js/sorttable.js"></script>

<!-- Plotly.js CDN -->
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/plotly.js/1.54.6/plotly.min.js"></script>

<!-- Load and display data -->
<script defer src="/static/assets/js/fetch-data.js"></script>
{% endblock javascripts %}